package models;
// Generated 24 mars 2014 10:24:07 by Hibernate Tools 3.6.0


import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Centres generated by hbm2java
 */
@Entity
@Table(name="centres")
public class Centres  implements java.io.Serializable {

	
	private static final long serialVersionUID = -731468984861123772L;
	@Id 
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id")
	private Integer centerId;
	
	@Column(name = "Adresse", columnDefinition="varchar(80) default '' ", nullable=true)
    private String centerAddress;
	
	@Column(name = "Arrondissement", columnDefinition="varchar(60) default '' ", nullable=true)
    private String centerArrondissement;
	
	@Column(name = "Boite_postale", columnDefinition="varchar(10) default '' ", nullable=true)
    private String centerBp;
	
	@Column(name = "Code", columnDefinition="varchar(10) default '' ", nullable=true)
    private String centerCode;
	
	@Column(name = "Circonscription", columnDefinition="varchar(80) default '' ", nullable=true)
    private String centerCollectivite;
	
	@Column(name = "Nom_Commune", columnDefinition="varchar(80) default '' ", nullable=true)
    private String commune;
	
	@Column(name = "Date_Install", columnDefinition="varchar(80) default '' ", nullable=true)
    private String date_Install;
	
	@Column(name = "Departement", columnDefinition="varchar(40) default '' ", nullable=true)
    private String centerDepartement;
    
	@Column(name = "Mail", columnDefinition="varchar(40) default '' ", nullable=true)
	private String centerMail;
	
	@Column(name = "Nom", columnDefinition="varchar(80) default '' ", nullable=true)
    private String centerName;
	
	@Column(name = "Telephone", columnDefinition="varchar(20) default '' ", nullable=true)
    private String centerPhone;
	
	@Column(name = "Centre_principal", columnDefinition="varchar(40) default '' ", nullable=true)
    private String mainCenter;
	
	@Column(name = "Region", columnDefinition="varchar(50) default '' ", nullable=true)
    private String centerRegion;
	
	@Column(name = "Type", columnDefinition="varchar(30) default '' ", nullable=true)
    private String centerType;
	
	
	@OneToMany(mappedBy="centre")
	private List<Licences> centre;
	
	


	public Centres() {
    }

    

    public Centres(String centerAddress, String centerArrondissement,
			String centerBp, String centerCode, String centerCollectivite,
			String commune, String date_Install, String centerDepartement,
			String centerMail, String centerName, String centerPhone,
			String mainCenter, String centerRegion, String centerType) {
		super();
		this.centerAddress = centerAddress;
		this.centerArrondissement = centerArrondissement;
		this.centerBp = centerBp;
		this.centerCode = centerCode;
		this.centerCollectivite = centerCollectivite;
		this.commune = commune;
		this.date_Install = date_Install;
		this.centerDepartement = centerDepartement;
		this.centerMail = centerMail;
		this.centerName = centerName;
		this.centerPhone = centerPhone;
		this.mainCenter = mainCenter;
		this.centerRegion = centerRegion;
		this.centerType = centerType;
	}



	public Integer getCenterId() {
        return this.centerId;
    }
    
    public void setCenterId(Integer centerId) {
        this.centerId = centerId;
    }

    public String getCenterAddress() {
        return this.centerAddress;
    }
    
    public void setCenterAddress(String centerAddress) {
        this.centerAddress = centerAddress;
    }

    public String getCenterArrondissement() {
        return this.centerArrondissement;
    }
    
    public void setCenterArrondissement(String centerArrondissement) {
        this.centerArrondissement = centerArrondissement;
    }

    
    public String getCenterBp() {
        return this.centerBp;
    }
    
    public void setCenterBp(String centerBp) {
        this.centerBp = centerBp;
    }


    public String getCenterCode() {
        return this.centerCode;
    }
    
    public void setCenterCode(String centerCode) {
        this.centerCode = centerCode;
    }

    public String getCenterCollectivite() {
        return this.centerCollectivite;
    }
    
    public void setCenterCollectivite(String centerCollectivite) {
        this.centerCollectivite = centerCollectivite;
    }

    public String getCenterDepartement() {
        return this.centerDepartement;
    }
    
    public void setCenterDepartement(String centerDepartement) {
        this.centerDepartement = centerDepartement;
    }

    public String getCenterMail() {
        return this.centerMail;
    }
    
    public void setCenterMail(String centerMail) {
        this.centerMail = centerMail;
    }

    public String getCenterName() {
        return this.centerName;
    }
    
    public void setCenterName(String centerName) {
        this.centerName = centerName;
    }

    public String getCenterPhone() {
        return this.centerPhone;
    }
    
    public void setCenterPhone(String centerPhone) {
        this.centerPhone = centerPhone;
    }

    
    public String getMainCenter() {
        return this.mainCenter;
    }
    
    public void setMainCenter(String mainCenter) {
        this.mainCenter = mainCenter;
    }

    public String getCenterRegion() {
        return this.centerRegion;
    }
    
    public void setCenterRegion(String centerRegion) {
        this.centerRegion = centerRegion;
    }

    public String getCenterType() {
        return this.centerType;
    }
    
    public void setCenterType(String centerType) {
        this.centerType = centerType;
    }

	

	/**
	 * @return the commune
	 */
	public String getCommune() {
		return commune;
	}

	/**
	 * @param commune the commune to set
	 */
	public void setCommune(String commune) {
		this.commune = commune;
	}

	/**
	 * @return the date_Install
	 */
	public String getDate_Install() {
		return date_Install;
	}

	/**
	 * @param date_Install the date_Install to set
	 */
	public void setDate_Install(String date_Install) {
		this.date_Install = date_Install;
	}
	
	
	

}


