package models;
// Generated 24 mars 2014 10:24:07 by Hibernate Tools 3.6.0


import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users")
public class Users  implements java.io.Serializable {


	private static final long serialVersionUID = -731468984861123772L;
	@Id 
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id")
    private Integer userId;
	
	@Column(name = "Adresse", columnDefinition="varchar(80) default '' ", nullable=true)
    private String userAddress;
	
	@Column(name = "Nom", columnDefinition="varchar(40) default '' ", nullable=true)
    private String userNom;
	
	@Column(name = "Sexe", columnDefinition="varchar(20) default '' ", nullable=true)
    private String sexe;
	
	@Column(name = "Courriel", columnDefinition="varchar(90) default '' ", nullable=true, unique = true)
    private String userMail;
	
	@Column(name = "Telephone", columnDefinition="varchar(20) default '' ", nullable=true)
    private String userNumTel;
	
	@Column(name = "Password", columnDefinition="varchar(200) default '' ", nullable=false)
    private String userPassword;
	
	@Column(name = "Prenom", columnDefinition="varchar(80) default '' ", nullable=false)
    private String userPrenom;
	
	@Column(name = "Profil", columnDefinition="varchar(30) default '' ", nullable=false)
    private String userProfil;
	
	@Column(name = "pseudo", columnDefinition="varchar(40) default '' ", nullable=false, unique = true)
    private String userUserName;

	@Column(name = "cni", columnDefinition="varchar(20) default '' ", nullable=false, unique = true)
    private String cni;
	
	@Column(name = "etat", columnDefinition="boolean default true", nullable=false)
    private boolean etat;
	
	

	@OneToMany(mappedBy="createlicence")
	private List<Licences> createlicence;
	
	
	

    public Users() {
    }

	
    public Users(String userUserName) {
        this.userUserName = userUserName;
    }
    public Users(String userAddress, String userNom, String userMail, String userNumTel, 
    		String userPassword, String userPrenom, String userProfil, String userUserName, String cni) {
       
       this.userAddress = userAddress;
       this.userNom = userNom;
       this.userMail = userMail;
       this.userNumTel = userNumTel;
       this.userPassword = userPassword;
       this.userPrenom = userPrenom;
       this.userProfil = userProfil;
       this.userUserName = userUserName;
       this.cni = cni;
    }


	public Integer getUserId() {
		return userId;
	}


	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	
	public String getUserAddress() {
		return userAddress;
	}


	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}


	public String getUserNom() {
		return userNom;
	}


	public void setUserNom(String userNom) {
		this.userNom = userNom;
	}

	public String getUserNumTel() {
		return userNumTel;
	}


	public void setUserNumTel(String userNumTel) {
		this.userNumTel = userNumTel;
	}


	public String getUserPassword() {
		return userPassword;
	}


	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}


	public String getUserPrenom() {
		return userPrenom;
	}


	public void setUserPrenom(String userPrenom) {
		this.userPrenom = userPrenom;
	}


	public String getUserProfil() {
		return userProfil;
	}


	public void setUserProfil(String userProfil) {
		this.userProfil = userProfil;
	}


	public String getUserUserName() {
		return userUserName;
	}


	public void setUserUserName(String userUserName) {
		this.userUserName = userUserName;
	}


	


	public String getSexe() {
		return sexe;
	}


	public void setSexe(String sexe) {
		this.sexe = sexe;
	}


	public String getCni() {
		return cni;
	}


	public void setCni(String cni) {
		this.cni = cni;
	}

	
	/**
	 * @return the etat
	 */
	public boolean isEtat() {
		return etat;
	}


	/**
	 * @param etat the etat to set
	 */
	public void setEtat(boolean etat) {
		this.etat = etat;
	}


	public String getUserMail() {
		return userMail;
	}


	public void setUserMail(String userMail) {
		this.userMail = userMail;
	}
	
	
     
}


